// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvVGYtvGZ3116sRILT84OCKZ2KtPGwvq4',
    appId: '1:1071032501584:web:6022219f0ac8e3342c1855',
    messagingSenderId: '1071032501584',
    projectId: 'todoapp-2eb92',
    authDomain: 'todoapp-2eb92.firebaseapp.com',
    storageBucket: 'todoapp-2eb92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoUEGQ2yDyezcldehMNWSPLa2VK48nFe4',
    appId: '1:1071032501584:android:5a0b14dc7d924fa12c1855',
    messagingSenderId: '1071032501584',
    projectId: 'todoapp-2eb92',
    storageBucket: 'todoapp-2eb92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxLNDmC4ytJ7OuZJQ5SyyFlgCwCaDFjGw',
    appId: '1:1071032501584:ios:0be75ecdc37337332c1855',
    messagingSenderId: '1071032501584',
    projectId: 'todoapp-2eb92',
    storageBucket: 'todoapp-2eb92.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxLNDmC4ytJ7OuZJQ5SyyFlgCwCaDFjGw',
    appId: '1:1071032501584:ios:0be75ecdc37337332c1855',
    messagingSenderId: '1071032501584',
    projectId: 'todoapp-2eb92',
    storageBucket: 'todoapp-2eb92.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
